# Generated by Django 4.2.5 on 2023-09-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='locattion',
            new_name='location',
        ),
    ]
